class Spell < ApplicationRecord
    belongs_to :buff
    has_many :spec_spells

    def self.seed
        dk = CharacterClass.find_by(name:"death_knight")
        paladin = CharacterClass.find_by(name:"paladin")
        shaman = CharacterClass.find_by(name:"shaman")
        mage = CharacterClass.find_by(name:"mage")
        warlock = CharacterClass.find_by(name:"warlock")
        priest = CharacterClass.find_by(name:"priest")
        druid = CharacterClass.find_by(name:"druid")
        hunter = CharacterClass.find_by(name:"hunter")
        rogue = CharacterClass.find_by(name:"rogue")
        warrior = CharacterClass.find_by(name:"warrior")

        spellList = [
            {name: "Abomination's Might", icon: "ability_warrior_intensifyrage", buff: Buff.find_by(name:"10% Attack Power"), specialization: [Specialization.find_by(name:"Blood")], description: "Increases the attack power by 10% of party and raid members within 100 yards.  Also increases your total Strength by 2%."},
            {name: "Trueshot Aura", icon: "ability_trueshot", buff: Buff.find_by(name:"10% Attack Power"), specialization: [Specialization.find_by(name:"Marksmanship")], description: "Increases the attack power of party and raid members within 100 yards by 10%.  Lasts until cancelled."},
            {name: "Unleashed Rage", icon: "spell_nature_unleashedrage", buff: Buff.find_by(name:"10% Attack Power"), specialization: [Specialization.find_by(name:"Enhancement")], description: "Increases your expertise by 9, and increases all party and raid members' attack power by 10% while within 100 yards of the Shaman."},
            {name: "Bloodlust/Heroism", icon: "spell_nature_bloodlust", buff: Buff.find_by(name:"Bloodlust/Heroism"), specialization: shaman.specializations, description: "Increases melee, ranged, and spell casting speed by 30% for all party and raid members.  Lasts 40 sec. After the completion of this effect, those affected will become Sated and unable to benefit from Bloodlust again for 10 min."},
            # BL castable by all shamans
            {name: "Wrath of Air Totem", icon: "spell_nature_slowingtotem", buff: Buff.find_by(name:"5% Spell Haste"), specialization: shaman.specializations, description: "Summons a Wrath of Air Totem with 5 health at the feet of the caster.  The totem provides 5% spell haste to all party and raid members within 30 yards.  Lasts 5 min."},
            # All shamans can cast wrath of air totem as well
            {name: "Leader of the Pack", icon: "spell_nature_unyeildingstamina", buff: Buff.find_by(name:"5% Physical Crit"), specialization: [Specialization.find_by(name:"Feral(Cat)"), Specialization.find_by(name:"Feral(Bear)")], description: "While in Cat, Bear, or Dire Bear Form, the Leader of the Pack increases critical strike chance of all party and raid members within 100 yards by 5%."},
            # LotP castable by Feral(Cat) & Feral(Bear)
            {name: "Rampage", icon: "ability_warrior_rampage", buff: Buff.find_by(name:"5% Physical Crit"), specialization: [Specialization.find_by(name:"Feral(Cat)")], description: "Increases ranged and melee critical hit chance of all party and raid members within 100 yds by 5%."},
            {name: "Tree of Life", icon: "ability_druid_treeoflife", buff: Buff.find_by(name:"6% Healing"), specialization: [druid.specializations.find_by(name:"Resto")], description: "Reduces the mana cost of your healing over time spells by 20% and grants the ability to shapeshift into the Tree of Life. While in this form you increase healing received by 6% for all party and raid members within 100 yards, and you can only cast Restoration spells in addition to Innervate, Barkskin, Nature's Grasp and Thorns spells."},
            {name: "Imp. Devotion Aura", icon: "spell_holy_devotionaura", buff: Buff.find_by(name:"6% Healing"), specialization: [Specialization.where(:name=>"Protection", :character_class_id=>paladin.id).first], description: "Increases the armor bonus of your Devotion Aura by 50% and increases the amount healed on any target affected by any of your Auras by 6%."},
            {name: "Blessing of Kings", icon: "spell_magic_magearmor", buff: Buff.find_by(name:"Blessing of Kings"), specialization: paladin.specializations, description: "Places a Blessing on the friendly target, increasing total stats by 10% for 10 min.  Players may only have one Blessing on them per Paladin at any one time."},
            # BoK castable by all paladins
            {name: "Moonkin Form", icon: "spell_nature_forceofnature", buff: Buff.find_by(name:"5% Spell Crit"), specialization: [Specialization.find_by(name:"Balance")], description: "Shapeshift into Moonkin Form.  While in this form the armor contribution from items is increased by 370%, damage taken while stunned is reduced by 15%, and all party and raid members within 100 yards have their spell critical chance increased by 5%.  Single target spell critical strikes in this form instantly regenerate 2% of your total mana.  The Moonkin can not cast healing or resurrection spells while shapeshifted."},
            {name: "Elemental Oath", icon: "spell_shaman_elementaloath", buff: Buff.find_by(name:"5% Spell Crit"), specialization: [Specialization.find_by(name:"Elemental")], description: "While Clearcasting from Elemental Focus is active, you deal 10% more spell damage. In addition, party and raid members within 100 yards receive a 5% bonus to their spell critical strike chance."},
            {name: "Imp. Windfury Totem", icon: "spell_nature_windfury", buff: Buff.find_by(name:"20% Melee Haste"), specialization: [Specialization.find_by(name:"Enhancement")], description: "Summons a Windfury Totem with 5 health at the feet of the caster.  The totem provides all party and raid members within 30 yards 20% melee haste.  Lasts 5 min."},
            {name: "Imp. Icy Talons", icon: "spell_deathknight_icytalons", buff: Buff.find_by(name:"20% Melee Haste"), specialization: [dk.specializations.find_by(name:"Frost")], description: "Increases the melee haste of all party and raid members within 100 yds by 20% and your haste by an additional 5%."},
            {name: "Ferocious Inspiration", icon: "ability_hunter_ferociousinspiration", buff: Buff.find_by(name:"3% Damage"), specialization: [Specialization.find_by(name:"Beast Mastery")], description: "All party and raid members have all damage increased by 3% within 100 yards of your pet. In addition, increases the damage dealt by Arcane Shot and Steady Shot by 9%."},
            {name: "Arcane Empowerment", icon: "spell_nature_starfall", buff: Buff.find_by(name:"3% Damage"), specialization: [Specialization.find_by(name:"Arcane")], description: "Increases the damage of your Arcane Missiles spell by an amount equal to 45% of your spell power and the damage of your Arcane Blast by 9% of your spell power.  In addition, increases the damage of all party and raid members within 100 yds by 3%."},
            {name: "Sanctified Retribution", icon: "spell_holy_mindvision", buff: Buff.find_by(name:"3% Damage"), specialization: [Specialization.find_by(name:"Retribution")], description: "Increases the damage caused by Retribution Aura by 50% and all damage caused by friendly targets affected by any of your Auras is increased by 3%."},
            {name: "Arcane Brilliance", icon: "spell_holy_arcaneintellect", buff: Buff.find_by(name:"Intellect"), specialization: mage.specializations, description: "Infuses all party and raid members with brilliance, increasing their Intellect by 60 for 1 hour."},
            # Arcane Brilliance castable by all mages
            {name: "Fel Intelligence (Int)", icon: "spell_shadow_brainwash", buff: Buff.find_by(name:"Intellect"), specialization: warlock.specializations, description: "Increases party and raid members Intellect by 48 and Spirit by 64."},
            {name: "Fel Intelligence (Spirit)", icon: "spell_shadow_brainwash", buff: Buff.find_by(name:"Spirit"), specialization: warlock.specializations, description: "Increases party and raid members Intellect by 48 and Spirit by 64."},
            # Fel Intelligence castable by all warlocks and also applies the Spirit buff
            {name: "Flametongue Totem", icon: "spell_nature_guardianward", buff: Buff.find_by(name:"Spell Power"), specialization: shaman.specializations, description: "Summons a Flametongue Totem with 5 health at the feet of the caster.  Party and raid members within 30 yards of the totem have their spell damage and healing increased by up to 144.  Lasts 5 min."},
            # Flametongue Totem also castable by Restoration shamans
            {name: "Totem of Wrath (Buff)", icon: "spell_fire_totemofwrath", buff: Buff.find_by(name:"Spell Power"), specialization: [Specialization.find_by(name:"Elemental")], description: "Summons a Totem of Wrath with 5 health at the feet of the caster.  The totem increases spell power by 280 for all party and raid members, and increases the critical strike chance of all attacks by 3% against all enemies within 40 yards.  Lasts 5 min."},
            {name: "Totem of Wrath (Debuff)", icon: "spell_fire_totemofwrath", buff: Buff.find_by(name:"+3% Crit"), specialization: [Specialization.find_by(name:"Elemental")], description: "Summons a Totem of Wrath with 5 health at the feet of the caster.  The totem increases spell power by 280 for all party and raid members, and increases the critical strike chance of all attacks by 3% against all enemies within 40 yards.  Lasts 5 min."},
            {name: "Demonic Pact", icon: "spell_shadow_demonicpact", buff: Buff.find_by(name:"Spell Power"), specialization: [Specialization.find_by(name:"Demonology")], description: "Increases your spell damage by 10%, and your pet's criticals apply the Demonic Pact effect to your party or raid members. Demonic Pact increases spell power by 10% of your Spell Damage for 45 sec. This effect has a 1 sec cooldown. Does not work on Subjugated demons."},
            {name: "Battle Shout", icon: "ability_warrior_battleshout", buff: Buff.find_by(name:"Attack Power"), specialization: warrior.specializations, description: "The warrior shouts, increasing attack power of all raid and party members within 30 yards by 550. Lasts 2 min."},
            # Battle Shout castable by all warriors
            {name: "Greater Blessing of Might", icon: "spell_holy_greaterblessingofkings", buff: Buff.find_by(name:"Attack Power"), specialization: paladin.specializations, description: "Gives all members of the raid or group that share the same class with the target the Greater Blessing of Might, increasing attack power by 550 for 30 min.  Players may only have one Blessing on them per Paladin at any one time."},
            # Greater Blessing of Might castable by all paladins
            {name: "Commanding Shout", icon: "ability_warrior_rallyingcry", buff: Buff.find_by(name:"Health"), specialization: warrior.specializations, description: "Increases maximum health of all party and raid members within 30 yards by 2255.  Lasts 2 min."},
            # Commanding Shout castable by all warriors
            {name: "Blood Pact", icon: "spell_shadow_bloodboil", buff: Buff.find_by(name:"Health"), specialization: warlock.specializations, description: "Increases party and raid members' health by 1330."},
            # Blood Pact castable by all warlocks
            {name:"Prayer of Spirit", icon: "spell_holy_prayerofspirit", buff: Buff.find_by(name:"Spirit"), specialization: priest.specializations, description: "Power infuses the target's party and raid members, increasing their Spirit by 80 for 1 hour."},
            # Prayer of Spirit castable by all priests
            {name:"Prayer of Fortitude", icon: "spell_holy_prayeroffortitude", buff: Buff.find_by(name:"Stamina"), specialization: priest.specializations, description: "Power infuses the target's party and raid members, increasing their Stamina by 165 for 1 hour."},
            # Prayer of Fortitude castable by all priests
            {name: "Swift Retribution", icon: "ability_paladin_swiftretribution", buff: Buff.find_by(name:"3% Haste"), specialization: [Specialization.find_by(name:"Retribution")], description: "Your auras also increase casting, ranged and melee attack speeds by 3%."},
            {name: "Imp. Moonkin Form", icon: "ability_druid_improvedmoonkinform", buff: Buff.find_by(name:"3% Haste"), specialization: [Specialization.find_by(name:"Balance")], description: "Your Moonkin Aura also causes affected targets to gain 3% haste and you to gain 30% of your spirit as additional spell damage."},
            {name: "Gift of the Wild", icon: "spell_nature_giftofthewild", buff: Buff.find_by(name:"Gift of the Wild"), specialization: druid.specializations, description: "Increases the friendly target's armor by 750, all attributes by 37 and all resistances by 54 for 1 hour."},
            # Gift of the Wild castable by all druids
            {name: "Horn of Winter", icon: "inv_misc_horn_02", buff: Buff.find_by(name:"Strength/Agility"), specialization: [Specialization.find_by(name:"Frost")], description: "The Death Knight blows the Horn of Winter, which generates 10 runic power and increases total Strength and Agility of all party or raid members within 30 yards by 155.  Lasts 2 min."},
            {name: "Strength of Earth Totem", icon: "spell_nature_earthbindtotem", buff: Buff.find_by(name:"Strength/Agility"), specialization: shaman.specializations, description: "Summons a Strength of Earth Totem with 5 health at the feet of the caster.  Party and raid members within 30 yards of the totem have their Strength and Agility increased by 155.  Lasts 5 min."},
            # Strength of Earth Totem castable by all shamans

            {name: "Unholy Frenzy", icon: "spell_deathknight_bladedarmor", buff: Buff.find_by(name:"Unholy Frenzy"), specialization: [Specialization.find_by(name:"Blood")], description: "Induces a friendly unit into a killing frenzy for 30 sec.  The target is Enraged, which increases their physical damage by 20%, but causes them to lose health equal to 1% of their maximum health every second."},
            {name: "Focus Magic", icon: "spell_arcane_studentofmagic", buff: Buff.find_by(name:"Focus Magic"), specialization: mage.specializations, description: "Increases the target's chance to critically hit with spells by 3%.  When the target critically hits your chance to critically hit with spells is increased by 3% for 10 sec.  Cannot be cast on self."},
            # Focus Magic castable by all mages
            {name: "Power Infusion", icon: "spell_holy_powerinfusion", buff: Buff.find_by(name:"Power Infusion"), specialization: [Specialization.find_by(name:"Discipline")], description: "Infuses the target with power, increasing spell casting speed by 20% and reducing the mana cost of all spells by 20%.  Lasts 15 sec."},
            {name: "Tricks of the Trade", icon: "ability_rogue_tricksofthetrade", buff: Buff.find_by(name:"Tricks of the Trade"), specialization: rogue.specializations, description: "The current party or raid member becomes the target of your Tricks of the Trade.  The threat caused by your next damaging attack and all actions taken for 6 sec afterwards will be transferred to the target.  In addition, all damage caused by the target is increased by 15% during this time."},
            # Tricks of the Trade castable by all rogues
            {name: "Inspiration", icon: "spell_holy_layonhands", buff: Buff.find_by(name:"10% Damage Reduction"), specialization: [Specialization.find_by(name:"Discipline")], description: "Reduces your target's physical damage taken by 10% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Penance, Prayer of Mending, Prayer of Healing, or Circle of Healing spell."},
            {name: "Ancestral Healing", icon: "spell_nature_undyingstrength", buff: Buff.find_by(name:"10% Damage Reduction"), specialization: [shaman.specializations.find_by(name:"Resto")], description: "Reduces your target's physical damage taken by 10% for 15 sec after getting a critical effect from one of your healing spells."},
            {name: "Blessing of Sanctuary", icon: "spell_nature_lightningshield", buff: Buff.find_by(name:"3% Damage Reduction"), specialization: [Specialization.where(:name=>"Protection", :character_class_id=>paladin.id).first], description: "Places a Blessing on the friendly target, reducing damage taken from all sources by 3% for 10 min and increasing strength and stamina by 10%.  In addition, when the target blocks, parries, or dodges a melee attack the target will gain 2% of maximum displayed mana."},
            {name: "Renewed Hope", icon: "spell_holy_holyprotection", buff: Buff.find_by(name:"3% Damage Reduction"), specialization: [Specialization.find_by(name: "Discipline")], description: "Increases the critical effect chance of your Flash Heal, Greater Heal and Penance (Heal) spells by 4% on targets afflicted by the Weakened Soul effect, and you have a 100% chance to reduce all damage taken by 3% for 1 min to all friendly party and raid targets when you cast Power Word: Shield. This effect has a 2 sec cooldown."},
            {name: "Divine Guardian", icon: "spell_holy_powerwordbarrier", buff: Buff.find_by(name:"10% Damage Reduction"), specialization: [Specialization.where(:name=>"Protection", :character_class_id=>paladin.id).first], description: "When Divine Sacrifice is activated, your party and raid members within 30 yards take 20% reduced damage for 6 sec.  In addition, increases the duration of your Sacred Shield by 100% and the amount absorbed by 20%."},
            {name: "Faerie Fire", icon: "spell_nature_faeriefire", buff: Buff.find_by(name:"5% Armor Reduction"), specialization: druid.specializations, description: "Decrease the armor of the target by 5% for 5 min.  While affected, the target cannot stealth or turn invisible."},
            {name: "Sting", icon: "spell_nature_slowpoison", buff: Buff.find_by(name:"5% Armor Reduction"), specialization: hunter.specializations, description: "Your wasp stings for 64 to 86 Nature damage, and decreases the armor of the target by 5% for 20 sec.  While affected, the target cannot stealth or turn invisible."},
            {name: "Curse of Weakness", icon: "spell_shadow_curseofmannoroth", buff: Buff.find_by(name:"5% Armor Reduction"), specialization: warlock.specializations, description: "Target's melee attack power is reduced by 478 and armor is reduced by 5% for 2 min.  Only one Curse per Warlock can be active on any one target."},
            {name: "Scorpid Sting", icon: "ability_hunter_criticalshot", buff: Buff.find_by(name:"3% Physical Hit Reduction"), specialization: hunter.specializations, description: "Stings the target, reducing chance to hit with melee and ranged attacks by 3% for 20 sec.  Only one Sting per Hunter can be active on any one target."},
            {name: "Insect Swarm", icon: "spell_nature_insectswarm", buff: Buff.find_by(name:"3% Physical Hit Reduction"), specialization: [Specialization.find_by(name:"Balance")], description: "The enemy target is swarmed by insects, decreasing their chance to hit with melee and ranged attacks by 3% and causing 1290 Nature damage over 12 sec."},
            {name: "Acid Spit", icon: "spell_nature_acid_01", buff: Buff.find_by(name:"20% Armor Reduction"), specialization: hunter.specializations, description: "Your worm spits acid at an enemy, causing 124 to 176 Nature damage and reducing its armor by 10% per Acid Spit for 30 sec.  Can be applied up to 2 times."},
            {name: "Expose Armor", icon: "ability_warrior_riposte", buff: Buff.find_by(name:"20% Armor Reduction"), specialization: rogue.specializations, description: "Finishing move that exposes the target, reducing armor by 20% and lasting longer per combo point"},
            {name: "Sunder Armor", icon: "ability_warrior_sunder", buff: Buff.find_by(name:"20% Armor Reduction"), specialization: warrior.specializations, description: "Sunders the target's armor, reducing it by 4% per Sunder Armor and causes a high amount of threat.  Threat increased by attack power.  Can be applied up to 5 times.  Lasts 30 sec."},
            {name: "Imp. Icy Touch", icon: "spell_deathknight_icetouch", buff: Buff.find_by(name:"20% Attack Speed Reduction"), specialization: [Specialization.find_by(name:"Blood"), Specialization.find_by(name:"Frost")], description: "Your Icy Touch does an additional 15% damage and your Frost Fever reduces melee and ranged attack speed by an additional 6%."},
            {name: "Infected Wounds", icon: "ability_druid_infectedwound", buff: Buff.find_by(name:"20% Attack Speed Reduction"), specialization: [Specialization.find_by(name:"Feral(Bear)")], description: "Your Shred, Maul, and Mangle attacks cause an Infected Wound in the target. The Infected Wound reduces the movement speed of the target by 50% and the attack speed by 20%. Lasts 12 sec."},
            {name: "Judgements of the Just", icon: "ability_paladin_judgementsofthejust", buff: Buff.find_by(name:"20% Attack Speed Reduction"), specialization: [Specialization.where(:name=>"Protection", :character_class_id=>paladin.id).first], description: "Reduces the cooldown of your Hammer of Justice by 10 sec, increases the duration of your Seal of Justice effect by 1 sec and your Judgement spells also reduce the melee attack speed of the target by 20%."},
            {name: "Imp. Thunder Clap", icon: "ability_thunderclap", buff: Buff.find_by(name:"20% Attack Speed Reduction"), specialization: warrior.specializations, description: "Blasts nearby enemies increasing the time between their attacks by 10% for 30 sec and doing 300 damage to them.  Damage increased by attack power.  This ability causes additional threat."},
            {name: "Imp. Shadow Bolt", icon: "spell_shadow_shadowbolt", buff: Buff.find_by(name:"+5% Spell Crit"), specialization: [Specialization.find_by(name:"Affliction"), Specialization.find_by(name:"Destruction")], description: "Increases the damage done by your Shadow Bolt spell by 10%, and your Shadow Bolt has a 100% chance to cause your target to be vulnerable to spell damage, increasing spell critical strike chance against that target by 5%. Effect lasts 30 sec."},
            {name: "Imp. Scorch", icon: "spell_fire_soulburn", buff: Buff.find_by(name:"+5% Spell Crit"), specialization: [Specialization.find_by(name:"Fire")], description: "Increases your chance to critically hit with Scorch, Fireball and Frostfire Bolt by an additional 3% and your damaging Scorch spells have a 100% chance to cause your target to be vulnerable to spell damage, increasing spell critical strike chance against that target by 5% and lasts 30 sec."},
            {name: "Winter's Chill", icon: "spell_frost_chillingblast", buff: Buff.find_by(name:"+5% Spell Crit"), specialization: [mage.specializations.find_by(name:"Frost")], description: "Increases your chance to critically hit with Frostbolt by an additional 3% and gives your Frost damage spells a 100% chance to apply the Winter's Chill effect, which increases the chance spells will critically hit the target by 1% for 15 sec.  Stacks up to 5 times."},
            {name: "Heart of the Crusader", icon: "spell_holy_holysmite", buff: Buff.find_by(name:"+3% Crit"), specialization: [Specialization.find_by(name:"Retribution")], description: "In addition to the normal effect, your Judgement spells will also increase the critical strike chance of all attacks made against that target by an additional 3%."},
            {name: "Master Poisoner", icon: "ability_creature_poison_06", buff: Buff.find_by(name:"+3% Crit"), specialization: [Specialization.find_by(name:"Assassination")], description: "Increases the critical hit chance of all attacks made against any target you have poisoned by 3%, reduces the duration of all Poison effects applied to you by 50%, and gives Envenom a 100% chance not to consume Deadly Poison."},
            {name: "Demoralizing Roar", icon: "classic_ability_druid_demoralizingroar", buff: Buff.find_by(name:"Attack Power Reduction"), specialization: [Specialization.find_by(name:"Feral(Bear)")], description: "The druid roars, decreasing nearby enemies' melee attack power by 411.  Lasts 30 sec."},
            {name: "Demoralizing Shout", icon: "ability_warrior_warcry", buff: Buff.find_by(name:"Attack Power Reduction"), specialization: warrior.specializations, description: "Reduces the melee attack power of all enemies within 10 yards by 411 for 30 sec."},
            {name: "Vindication", icon: "spell_holy_vindication", buff: Buff.find_by(name:"Attack Power Reduction"), specialization: [Specialization.where(:name=>"Protection", :character_class_id=>paladin.id).first, Specialization.find_by(name:"Retribution")], description: "Gives the Paladin's damaging attacks a chance to reduce the target's attack power by 574 for 10 sec."},
            {name: "Curse of Weakness", icon: "spell_shadow_curseofmannoroth", buff: Buff.find_by(name:"Attack Power Reduction"), specialization: warlock.specializations, description: "Target's melee attack power is reduced by 478 and armor is reduced by 5% for 2 min.  Only one Curse per Warlock can be active on any one target."},
            {name: "Savage Combat", icon: "ability_creature_disease_03", buff: Buff.find_by(name:"+4% Physical Damage"), specialization: [Specialization.find_by(name:"Combat")], description: "Increases your total attack power by 4% and all physical damage caused to enemies you have poisoned is increased by 4%."},
            {name: "Blood Frenzy", icon: "ability_warrior_bloodfrenzy", buff: Buff.find_by(name:"+4% Physical Damage"), specialization: [Specialization.find_by(name:"Arms")], description: "Increases your melee attack speed by 10%.  In addition your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 4%."},
            {name: "Misery", icon: "spell_shadow_misery", buff: Buff.find_by(name:"+3% Spell Hit"), specialization: [Specialization.find_by(name:"Shadow")], description: "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also increase the chance for harmful spells to hit by 3% lasting 24 sec, and increases the benefit from spell power gained by your Mind Blast, Mind Flay and Mind Sear spells by 15%."},
            {name: "Imp. Faerie Fire", icon: "spell_nature_faeriefire", buff: Buff.find_by(name:"+3% Spell Hit"), specialization: [Specialization.find_by(name:"Balance")] , description: "Your Faerie Fire spell also increases the chance the target will be hit by spell attacks by 3%, and increases the critical strike chance of your damage spells by 3% on targets afflicted by Faerie Fire."},
            {name: "Mangle", icon: "ability_druid_mangle2", buff: Buff.find_by(name:"+30% Bleed Damage"), specialization: [Specialization.find_by(name:"Feral(Bear)"), Specialization.find_by(name:"Feral(Cat)")], description: "Mangle the target, inflicting damage and causing the target to take additional damage from bleed effects for 1 min.  This ability can be used in Cat Form or Dire Bear Form."},
            {name: "Trauma", icon: "ability_warrior_bloodnova", buff: Buff.find_by(name:"+30% Bleed Damage"), specialization: [Specialization.find_by(name:"Arms")], description: "Your melee critical strikes increase the effectiveness of Bleed effects on the target by 30% for 1 min."},
            {name: "Curse of the Elements", icon: "spell_shadow_chilltouch", buff: Buff.find_by(name:"+13% Spell Damage"), specialization: warlock.specializations, description: "Curses the target for 5 min, reducing Arcane, Fire, Frost, Nature, and Shadow resistances by 165 and increasing magic damage taken by 13%.  Only one Curse per Warlock can be active on any one target."},
            {name: "Ebon Plaguebringer", icon: "ability_creature_cursed_03", buff: Buff.find_by(name:"+13% Spell Damage"), specialization: [Specialization.find_by(name:"Unholy")], description: "Your Crypt Fever morphs into Ebon Plague, which increases magic damage taken by 13% in addition to increasing disease damage taken.  Improves your critical strike chance with weapons and spells by 3% at all times."},
            {name: "Earth and Moon", icon: "ability_druid_earthandsky", buff: Buff.find_by(name:"+13% Spell Damage"), specialization: [Specialization.find_by(name:"Balance")], description: "Your Wrath and Starfire spells have a 100% chance to apply the Earth and Moon effect, which increases spell damage taken by 13% for 12 sec.  Also increases your spell damage by 6%."},
            {name: "Mana Tide Totem", icon: "spell_frost_summonwaterelemental", buff: Buff.find_by(name:"Mana Tide Totem"), specialization: [shaman.specializations.find_by(name:"Resto")], description: "Summons a Mana Tide Totem with 10% of the caster's health at the feet of the caster for 12 sec that restores 6% of total mana every 3 seconds to group members within 30 yards."},
            {name: "Innervate", icon: "spell_nature_lightning", buff: Buff.find_by(name:"Innervate"), specialization: druid.specializations, description: "Causes the target to regenerate mana equal to 225% of the casting Druid's base mana pool over 10 sec."},
            {name: "Judgements of the Wise", icon: "ability_paladin_judgementofthewise", buff: Buff.find_by(name:"Replenishment"), specialization: [Specialization.find_by(name:"Retribution")], description: "Your damaging Judgement spells have a 100% chance to grant the Replenishment effect to up to 10 party or raid members mana regeneration equal to 1% of their maximum mana per 5 sec for 15 sec, and to immediately grant you 25% of your base mana."},
            {name: "Vampiric Touch", icon: "spell_holy_stoicism", buff: Buff.find_by(name:"Replenishment"), specialization: [Specialization.find_by(name:"Shadow")], description: "Causes 850 Shadow damage over 15 sec to your target and causes up to 10 party or raid members to gain 1% of their maximum mana per 5 sec when you deal damage from Mind Blast. In addition, if the Vampiric Touch is dispelled it will cause 1360 damage to the afflicted target."},
            {name: "Imp. Soul Leech", icon: "ability_warlock_improvedsoulleech", buff: Buff.find_by(name:"Replenishment"), specialization: [Specialization.find_by(name:"Destruction")], description: "Your Soul Leech effect also restores mana to you and your summoned demon equal to 2% of maximum mana, and has a 100% chance to grant up to 10 party or raid members mana regeneration equal to 1% of maximum mana per 5 sec. Lasts for 15 sec."},
            {name: "Hunting Party", icon: "ability_hunter_huntingparty", buff: Buff.find_by(name:"Replenishment"), specialization: [Specialization.find_by(name:"Survival")], description: "Increases your total Agility by an additional 3%, and your Arcane Shot, Explosive Shot and Steady Shot critical strikes have a 100% chance to grant up to 10 party or raid members mana regeneration equal to 1% of the maximum mana per 5 sec. Lasts for 15 sec."},
            {name: "Enduring Winter", icon: "spell_frost_summonwaterelemental_2", buff: Buff.find_by(name:"Replenishment"), specialization: [mage.specializations.find_by(name:"Frost")], description: "Increases the duration of your Summon Water Elemental spell by 15 sec and your Frostbolt spell has a 100% chance to grant up to 10 party or raid members mana regeneration equal to 1% of their maximum mana per 5 sec for 15 sec.  This effect cannot occur more often than once every 6 sec."},
            {name: "Rapture", icon: "spell_holy_rapture", buff: Buff.find_by(name:"Rapture"), specialization: [Specialization.find_by(name:"Discipline")], description: "When your Power Word: Shield is completely absorbed or dispelled you are instantly energized with 2.5% of your total mana, and you have a 100% chance to energize your shielded target with 2% total mana, 8 rage, 16 energy or 32 runic power. This effect can only occur once every 12 sec."},
            {name: "Revitalize", icon: "ability_druid_replenish", buff: Buff.find_by(name:"Revitalize"), specialization: [druid.specializations.find_by(name:"Resto")], description: "Your Rejuvenation and Wild Growth spells have a 15% chance to restore 8 Energy, 4 Rage, 1% Mana or 16 Runic Power per tick."},
            {name: "Greater Blessing of Wisdom", icon: "spell_holy_greaterblessingofwisdom", buff: Buff.find_by(name:"Mana Regen"), specialization: paladin.specializations, description: "Gives all members of the raid or group that share the same class with the target the Greater Blessing of Wisdom, restoring 92 mana every 5 seconds for 30 min.  Players may only have one Blessing on them per Paladin at any one time."},
            {name: "Mana Spring Totem", icon: "spell_nature_manaregentotem", buff: Buff.find_by(name:"Mana Regen"), specialization: shaman.specializations, description: "Summons a Mana Spring Totem with 5 health at the feet of the caster for 5 min that restores 91 mana every 5 seconds to all party and raid members within 30 yards."},
            {name: "Judgement of Wisdom", icon: "ability_paladin_judgementblue", buff: Buff.find_by(name:"Judgement of Wisdom"), specialization: paladin.specializations, description: "Unleashes the energy of a Seal spell to judge an enemy for 20 sec, giving each attack a chance to restore 2% of the attacker's base mana.  Refer to individual Seals for additional Judgement effect.  Only one Judgement per Paladin can be active at any one time."},
            {name: "Hymn of Hope", icon: "spell_holy_symbolofhope", buff: Buff.find_by(name:"Hymn of Hope"), specialization: priest.specializations, description: "Restores 3% mana to 3 nearby low mana friendly party or raid targets every 2 sec for 8 sec, and increases their total maximum mana by 20% for 8 sec. Maximum of 12 mana restores. The Priest must channel to maintain the spell."},
            {name: "Vampiric Embrace", icon: "spell_shadow_unsummonbuilding", buff: Buff.find_by(name:"Vampiric Embrace"), specialization: [Specialization.find_by(name:"Shadow")], description: "Fills you with the embrace of Shadow energy, causing you to be healed for 15% and other party members to be healed for 3% of any single-target Shadow spell damage you deal for 30 min."},
            {name: "Judgement of Light", icon: "spell_holy_righteousfury", buff: Buff.find_by(name:"Judgement of Light"), specialization: paladin.specializations, description: "Unleashes the energy of a Seal spell to judge an enemy for 20 sec, granting attacks made against the judged enemy a chance of healing the attacker for 2% of their maximum health.  Refer to individual Seals for additional Judgement effect.  Only one Judgement per Paladin can be active at any one time."},
            {name: "Imp. Leader of the Pack", icon: "spell_nature_unyeildingstamina", buff: Buff.find_by(name:"Improved Leader of the Pack"), specialization: [Specialization.find_by(name:"Feral(Cat)"), Specialization.find_by(name:"Feral(Bear)")], description: "Your Leader of the Pack ability also causes affected targets to heal themselves for 4% of their total health when they critically hit with a melee or ranged attack.  The healing effect cannot occur more than once every 6 sec.  In addition, you gain 8% of your maximum mana when you benefit from this heal."},
            {name: "Healing Stream Totem", icon: "inv_spear_04", buff: Buff.find_by(name:"Healing Stream Totem"), specialization: shaman.specializations, description: "Summons a Healing Stream Totem with 5 health at the feet of the caster for 5 min that heals group members within 30 yards for 25 every 2 seconds."},
        ]   

        spellList.each do |spell|
            if Spell.find_by(name: spell[:name])
                next
            end
            Spell.create!(name: spell[:name], icon: spell[:icon], buff_id: spell[:buff].id, description: spell[:description])
            spell[:specialization].each do |spec|
                spec.spells << Spell.last
            end
        end
    end
end